### PR TITLE
refactor: few updates to have the functionality on-par with sentence-transformers and other minor updates

### PR DESCRIPTION
**Pull request by racinmat**
This PR adds
- correct library name passed to HF hub
- correct logic for local files only
- updated dependency to correspond to newer feature
- update target device since it's renamed since the 2.3.0 which we want to upgrade to
- correctly reverting the rename in https://github.com/xlang-ai/instructor-embedding/pull/92/files#diff-be933616f0a753fcc327eb42ce21506dbb991cc001e6831d3dfe0bcabcae33e0L23-R24

I locally ran the code for both local model and downloading from HF hub and it works well.

### CODE REVIEW

**Comment by racinmat** [comment]
@BBC-Esq let me know if this PR makes sense to you, and you can merge it so it also gets to the main repo.

**Comment by BBC-Esq** [comment]
Sorry for the slow response.  I won't have time to review this due to work.  Are you able to push the lazy blokes at the Instructor repo to accept my pull request and then perhaps you can submit your modification?  Alternatively, I'm not sure if it's possible to simply submit your change to them directly even if they're lacy in accepting mine?  I'm not a programmer by trade!  Chat gpt 4 taught me!  ;-)

**Comment by racinmat** [comment]
I see, no problem. I'm afraid I'm not able to push them if they are not answering to you.
Yes, I could make a direct PR to them with both changes, and I will do it now, so we'll increase the chance of merging at least one PR.

If you merge this PR, it will add my changes to your PR and thus if they merge all the changes will be there.

**Comment by BBC-Esq** [comment]
Hey, I just totally forgot about this dude.  My bad.  I'll take a look by tomorrow.  I had some personal stuff and work stuff and then this just flew by.  Nice to meet ya.

**Pull request merged**
